#!/bin/sh

opkg_uci_default_dir="/usr/lib/opkg/uci-default"

[ -n "${IPKG_INSTROOT}" ] || {
	[ ! -d ${opkg_uci_default_dir} ] && {
		mkdir -p ${opkg_uci_default_dir} 
	} 
	cp -a /etc/uci-defaults/luci-theme-48-r3000_Jiesai ${opkg_uci_default_dir}/luci-theme-90-config

	( . /etc/uci-defaults/luci-theme-48-r3000_Jiesai) &&	rm -f /etc/uci-defaults/luci-theme-48-r3000_Jiesai
}

exit 0
