#!/bin/sh

# product type: w and wv -- wv has the voip function

hostname=""
portmaps=""
portmaps_wifi=""
name=""

[ -f /tmp/sysinfo/board_name ] && name=$(cat /tmp/sysinfo/board_name) 
case "$name" in
	rl-ans5001*) 
		hostname="ANS5001" 
		portmaps="lan1"
		;;
	rl-ans5004*) 
		hostname="ANS5004"
		portmaps="lan1 lan2 lan3 lan4"
		;;
esac


if [ -f  /etc/config/wireless ] ; then
	hostname="$hostname""W"
	portmaps_wifi="wlan1 wlan2"
	uci batch <<-EOF
		set wireless.wifi_RF.countryid=156
		commit wireless	
	EOF
else
	hostname="$hostname""R"
	portmaps_wifi=""
fi

portmaps="$portmaps""$portmaps_wifi"

uci batch <<-EOF
	set luci.themes.r3000_ODM=/luci-static/r3000_ODM
	set luci.main.mediaurlbase=/luci-static/r3000_ODM
        commit luci
	delete wanctl.wanlink_0
	commit wanctl
	add wanctl wanlink
	set wanctl.wanlink_0.VlanID=-1
	set wanctl.wanlink_0.Cos=0
	set wanctl.wanlink_0.Servicemode=0
	set wanctl.wanlink_0.Mode=0
	set wanctl.wanlink_0.PortMap="$portmaps"
	commit wanctl
	set system.system_0.hostname="$hostname"
	commit system
EOF
	
echo "/etc/config/wanctl" >/usr/lib/opkg/keep.conf
#compatible the old production version 
echo "$hostname" > /proc/sys/kernel/hostname
#echo "DeviceName=$hostname" > /tmp/MME_devinfo
sed -i 's/\(DeviceName=\)[^\n]*/\1'"${hostname}"'/g' /tmp/MME_devinfo
exit 0
