#!/bin/sh
opkg_uci_default_dir="/usr/lib/opkg/uci-default"
[ -n "${IPKG_INSTROOT}" ] || {
	[ ! -d ${opkg_uci_default_dir} ] && {
		mkdir -p ${opkg_uci_default_dir} 
	} 
	cp -a /etc/uci-defaults/luci-theme-42-r3000_RL ${opkg_uci_default_dir}/luci-theme-90-config

	( . /etc/uci-defaults/luci-theme-42-r3000_RL) &&	rm -f /etc/uci-defaults/luci-theme-42-r3000_RL
}

exit 0
