#!/bin/sh

# product type: w and wv -- wv has the voip function
local hostname
if [ -f  /etc/config/voip ] ; then
	hostname="ANS4003WV"
else
	hostname="ANS4003W"
fi
uci batch <<-EOF
	set luci.themes.r3000_Turkey=/luci-static/r3000_Turkey
	set luci.main.mediaurlbase=/luci-static/r3000_Turkey
        commit luci
	delete wanctl.wanlink_0
	commit wanctl
	add wanctl wanlink
	set wanctl.wanlink_0.VlanID=-1
	set wanctl.wanlink_0.Cos=0
	set wanctl.wanlink_0.Servicemode=0
	set wanctl.wanlink_0.Mode=0
	set wanctl.wanlink_0.PortMap="lan1 lan2 lan3 wlan1 wlan2"
	commit wanctl
	set system.system_0.hostname="$hostname"
	commit system
EOF
	
echo "/etc/config/wanctl" >/usr/lib/opkg/keep.conf
#compatible the old production version 
echo "$hostname" > /proc/sys/kernel/hostname
#echo "DeviceName=$hostname" > /tmp/MME_devinfo
sed -i 's/\(DeviceName=\)[^\n]*/\1'"${hostname}"'/g' /tmp/MME_devinfo
