#!/bin/sh

# running after package install
# running before the ipk reserve
# product type: w and wv -- wv has the voip function
# product : use for Thailand country,
# history :
#	configuration:
#		web theme - ODM
#		wifi country: 764
#		wanctl:
#		sysname: ANS5004W or ANS5004R
	
local hostname
local portmaps

if [ -f  /etc/config/wireless ] ; then
	hostname="ANS5004W"
	portmaps="lan1 lan2 lan3 lan4 wlan1 wlan2"
#	uci batch <<-EOF
#		set wireless.wifi_RF.countryid=764
#		commit wireless 
#	EOF
	uci batch <<-EOF
		set wireless.wifi_RF.countryid=764
		commit wireless 
	EOF
else
	hostname="ANS5004R"
	portmaps="lan1 lan2 lan3 lan4"
fi

uci batch <<-EOF
	set luci.themes.r3000_Thailand=/luci-static/r3000_Thailand
	set luci.main.mediaurlbase=/luci-static/r3000_Thailand
        commit luci
	delete wanctl.wanlink_0
	commit wanctl
	add wanctl wanlink
	set wanctl.wanlink_0.VlanID=-1
	set wanctl.wanlink_0.Cos=0
	set wanctl.wanlink_0.Servicemode=0
	set wanctl.wanlink_0.Mode=0
	set wanctl.wanlink_0.PortMap="$portmaps"
	commit wanctl
	set system.system_0.hostname="$hostname"
	commit system
EOF
	
echo "/etc/config/wanctl" >/usr/lib/opkg/keep.conf
#compatible the old production version 
echo "$hostname" > /proc/sys/kernel/hostname
#echo "DeviceName=$hostname" > /tmp/MME_devinfo
sed -i 's/\(DeviceName=\)[^\n]*/\1'"${hostname}"'/g' /tmp/MME_devinfo
exit 0
