#!/bin/sh 

#[ -n "${IPKG_INSTROOT}" ] || {
    (cat /etc/passwd|grep failsafe) || \
        (echo R3000; sleep 1; echo R3000) | adduser -s /bin/false -h /nonexist failsafe > /dev/null 2>&1
	exit 0
#}

